ipex flag is deprecated, will be removed in Accelerate v1.10. From 2.7.0, PyTorch has all needed optimizations for Intel CPU and XPU.
/opt/conda/envs/linc/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:492: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Selected Tasks: ['folio-baseline-1shot']
Loading the model and tokenizer from HF (in bf16)
Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]Loading checkpoint shards:  14%|█▍        | 1/7 [00:03<00:20,  3.37s/it]Loading checkpoint shards:  29%|██▊       | 2/7 [00:06<00:15,  3.19s/it]Loading checkpoint shards:  43%|████▎     | 3/7 [00:09<00:13,  3.35s/it]Loading checkpoint shards:  57%|█████▋    | 4/7 [00:14<00:11,  3.83s/it]Loading checkpoint shards:  71%|███████▏  | 5/7 [00:19<00:08,  4.21s/it]Loading checkpoint shards:  86%|████████▌ | 6/7 [00:26<00:05,  5.33s/it]Loading checkpoint shards: 100%|██████████| 7/7 [00:30<00:00,  4.66s/it]Loading checkpoint shards: 100%|██████████| 7/7 [00:30<00:00,  4.33s/it]
/opt/conda/envs/linc/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:999: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
number of problems for this task is 3
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/app/linc-reimplementation/runner.py", line 125, in <module>
    main()
  File "/app/linc-reimplementation/runner.py", line 111, in main
    results[task] = evaluator.evaluate(task)
  File "/app/linc-reimplementation/eval/evaluator.py", line 48, in evaluate
    generations_prc, generations_raw, references = self.generate_text(task_name)
  File "/app/linc-reimplementation/eval/evaluator.py", line 88, in generate_text
    generations_prc, generations_raw = parallel_generations(
  File "/app/linc-reimplementation/eval/generation.py", line 91, in parallel_generations
    generations_prc, generations_raw = complete_code(
  File "/app/linc-reimplementation/eval/utils.py", line 119, in complete_code
    for step, batch in tqdm(
  File "/opt/conda/envs/linc/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/linc/lib/python3.10/site-packages/accelerate/data_loader.py", line 888, in __iter__
    raise ValueError(
ValueError: Batch does not contain any data (`None`). At the end of all iterable data available before expected stop iteration.
Traceback (most recent call last):
  File "/opt/conda/envs/linc/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/linc/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/opt/conda/envs/linc/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1199, in launch_command
    simple_launcher(args)
  File "/opt/conda/envs/linc/lib/python3.10/site-packages/accelerate/commands/launch.py", line 785, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/linc/bin/python', 'runner.py', '--model', 'bigcode/starcoderplus', '--precision', 'bf16', '--use_auth_token', '--tasks', 'folio-baseline-1shot', '--n_samples', '3', '--batch_size', '5', '--max_length_generation', '8192', '--temperature', '0.8', '--allow_code_execution', '--trust_remote_code', '--output_dir', 'outputs', '--limit', '3', '--save_generations_raw', '--save_generations_raw_path', 'starcoderplus_folio-baseline-1shot_generations_raw.json', '--save_generations_prc', '--save_generations_prc_path', 'starcoderplus_folio-baseline-1shot_generations_prc.json', '--save_references', '--save_references_path', 'starcoderplus_folio-baseline-1shot_references.json', '--save_results', '--save_results_path', 'starcoderplus_folio-baseline-1shot_results.json']' returned non-zero exit status 1.
